process-engine/consumer_api_client

package.json, src/consumer_api_client_service.ts
_✔︎ depended on https://github.com/process-engine/consumer_api_contracts/pull/8_
I updated the usage of the contracts to reflect the changes made in https://github.com/process-engine/consumer_api_contracts/pull/8
You can now build the client with version 0.3.0 of the consumer_api_contracts
=> ⬆️ Update contracts-usage

package.json, src/consumer_api_client_service.ts
Add call to the http route for retrieving a correlations results.
Call the function.
=> Implement function for retrieving a correlations results

package.json, src/consumer_api_client_service.ts
- Update all dependency major versions.
- Remove unused references and imports 
=> WIP: Feature/update major for data model dependencies

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
1. Added `socket.io-client` to dependencies.
2. Added method `initializeSocket` to `ConsumerApiClient` to allow for socket initialization with a specific identity used for all socket communication.
3. Implemented methods `onUserTaskWaiting`, `onUserTaskFinished`, `onProcessTerminated` and `onProcessEnded` on `InternalAccessor`, `ExternalAccessor` and `ConsumerApiClient` to subscribe for new message types.
**Issues:**
https://github.com/process-engine/process_engine_runtime/issues/71
PR: #18 
---
See https://github.com/process-engine/consumer_api_meta/pull/48.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at the …
=> ✨ Add async notifications

package.json
**Changes:**
1. Add the `name` field to the UserTask type. 
2. Update gulp to v4.0.0 to close vulnerabilities.
**Issues:**
PR: #20
Use the client to retrieve UserTasks and see that they now contain the name of each UserTask.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some typos
- ...
**Issues:**
Closes …
=> ✨ Add a name field to the UserTask

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
1. Use Instance IDs for UserTask Events, instead of ModelIds.
* This ensures that only one UserTask can ever be finished by a single request.
2. Add missing `socket.io-client` dependency.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
Closes #22 
PR: #21
Use the client to make requests for finishing UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part of this pull …
=> ♻️🔒 Use unique ids for UserTask events

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
Implement the `triggerMessageEvent` and `triggerSignalEvent` functions.
**Issues:**
Relates to: process-engine/process_engine_runtime#112
PR: #24
Use the client to trigger signals and messages.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: …
=> ✨Implement Event API

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #25
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some typos
- ...
**Issues:**
Closes …
=> 🔒 Add Identity to Events

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
1. Add ManualTask methods to External Accessor
2. Add ManualTask methods to Internal Accessor
3. Add ManualTask methods to ConsumerApiClientService
**Issues:**
Closes https://github.com/process-engine/process_engine_runtime/issues/91
PR: #23
---
See the [examples](#example) for inspiration.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just …
=> ✨Implement ManualTask

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
---
**Changes:**
1. Add a method which calls a callback when a ProcessInstance starts.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #26
---
See the [examples](#example) for inspiration.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> ✨ Implement ProcessStarted Notification

package.json
**Changes:**
1. Add get token by ProcessInstanceId functionality
PR: #28 
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some typos
- ...
**Issues:**
Closes #NumberOfFixedIssue
PR: #NumberOfThisPR
</code>
</pre>
</details> …
=> ✨ Add Get Token By ProcessInstanceId Functionality

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/consumer_api_client_service.ts
**Changes:**
Update all type references to the new structure used by the `ConsumerApiContracts` package.
PR: #29
This only changes the type imports, so all should run as before.
=> ♻️ 💄 Refactor Namespaces and API interfaces

dotnet/src/IdentityFactory.cs, dotnet/src/ProcessEngine.ConsumerAPI.Client.csproj, dotnet/src/ProcessEngineHttpClientFactory.cs, dotnet/tests/ProcessEngine.ConsumerAPI.Client.Tests.csproj
**Changes:**
1. Updated package to use EssentialProjects.IAM.Contracts@0.1.3
PR: #33
=> 🔼 Update EssentialProjects.IAM.Contracts package references

Jenkinsfile-js, javascript/.npmignore, javascript/index.js, javascript/package.json, javascript/webpack.config.js
**Changes:**
1. :sparkles: Add JavaScript Client
PR: #36 
=> :sparkles: Add JavaScript Client

Jenkinsfile-dotnet
**Changes:**
1. Publish all branches to MyGet.
2. Use Master Version of ProcessEngine Runtime Docker Image
**Issues:**
PR: #37
---
See the [examples](#example) for inspiration.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes some …
=> :construction_worker: Implement Feature Branch Publishing For .NET

typescript/tsconfig.json
**Changes:**
Using es2017 here prevents the client from being included with angular applications, since angular uses its own Promise-implementation, which handles the async/await pattern differently.
PR: #44
the client should work as before.
=> ⬇️ Transpile .ts client to es2015

dotnet/src/ConsumerApiClientService.cs, dotnet/src/ProcessEngine.ConsumerAPI.Client.csproj, dotnet/tests/ConsumerAPIService/GetEventsForCorrelationTests.cs, dotnet/tests/ConsumerAPIService/GetEventsForProcessModelInCorrelationTests.cs, dotnet/tests/ConsumerAPIService/GetEventsForProcessModelTests.cs, dotnet/tests/ConsumerAPIService/GetProcessResultForCorrelationTests.cs, dotnet/tests/ConsumerAPIService/StartProcessInstanceTests.cs, dotnet/tests/ConsumerAPIService/TriggerMessageEventTests.cs, dotnet/tests/ConsumerAPIService/TriggerSignalEventTests.cs, dotnet/tests/ProcessEngine.ConsumerAPI.Client.Tests.csproj, dotnet/tests/bpmn/test_consumer_api_message_event.bpmn, dotnet/tests/bpmn/test_consumer_api_signal_event.bpmn
**Changes:**
1. Added implementation for methods of the EventConsumer API
2. Added tests for the implemented methods
3. Set alias for `RestSettings` to make code more understandable
PR: #43 
Run the tests.
=> ✨ Implement .NET EventConsumer API

javascript/package.json
Update all dependencies for the JS bundle.
PR: #48
Install and use the bundle somewhere.
=> ⬆️ Update bundle

.gitignore, Jenkinsfile, Jenkinsfile-js, javascript/package-lock.json, typescript/package-lock.json, typescript/package.json
1. Switch from normal install to clean install
2. Remove package-lock from gitignore
3. Add package-lock
PR: #50 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> Switch from install to clean install

Jenkinsfile, typescript/package-lock.json, typescript/package.json, typescript/src/accessors/external_accessor.ts, typescript/src/accessors/internal_accessor.ts, typescript/src/consumer_api_client_service.ts
1. Add `onProcessError` notification
2. Only run `npm ci` on Jenkins builds, if the build runs on the `master` or `develop` branch
- This is required for working with feature branches, or else we would have to rewrite the package-lock after every change we make to a referenced dependency
Part of https://github.com/process-engine/process_engine_runtime/issues/348
PR: #51
=> ✨Add onProcessError notification

Jenkinsfile, typescript/package.json
1. Use New Release Process
PR: #56
=> ✨ Use New Release Process

typescript/package.json, typescript/src/accessors/external_accessor.ts, typescript/src/accessors/internal_accessor.ts, typescript/src/consumer_api_client.ts
1. Make Payload Optional for StartProcessInstance
Related to process-engine/process_engine_runtime#371
PR: #58
=> ♻️ Make Payload Optional for StartProcessInstance

typescript/package.json, typescript/src/accessors/external_accessor.ts, typescript/src/accessors/internal_accessor.ts, typescript/src/consumer_api_client.ts
1. Add Get Tasks Functionality
Related to https://github.com/process-engine/process_engine_runtime/issues/380
PR: #60
=> ✨ Add Get Tasks Functionality

typescript/package.json, typescript/src/accessors/external_accessor.ts, typescript/src/accessors/internal_accessor.ts, typescript/src/consumer_api_client.ts
1. Remove all the deprecated `CallActivity` notifications
PR: #64
=>  🔥 Remove CallActivity notifications

.github/workflows/publish-dotnet.yml, javascript/package.json, typescript/package.json
1. Fix escaping the branch name 
PR: #68 
Look at the build
=> 🐛 Use the regex global

dotnet/src/ConsumerApiClientService.cs, dotnet/src/ExternalTaskWorker.cs, dotnet/src/ProcessEngine.ConsumerAPI.Client.csproj, dotnet/tests/ProcessEngine.ConsumerAPI.Client.Tests.csproj, javascript/package-lock.json, javascript/package.json, typescript/package.json, typescript/src/accessors/external_accessor.ts, typescript/src/accessors/internal_accessor.ts, typescript/src/consumer_api_client.ts
1. Account for `errorMessage` and `errorCode` properties in ExternalTask requests
2. Fix some reference errors (.NET only)
Part of https://github.com/process-engine/process_engine_runtime/issues/493
PR: #69
- Run a Process that uses ExternalTasks with ErrorBoundaryEvents
- Provoke an error that can be intercepted by the BoundaryEvent
- See that it works
=> 🐛 Fix handling of customized ExternalTaskErrors

javascript/package-lock.json, javascript/package.json, typescript/src/external_task_worker.ts
1. Update javascript bundle
2. Fix usage of internal identity in NodeJS client
PR: #72
=> 🐛 Fix usage of internal identity in NodeJS client
